# -*- coding: utf-8 -*-
"""IT Automation with Python - Final Project 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17kD6v5w9lDGPKtpV1iNSfD7YY0RsyaBv
"""

#!/usr/bin/env python3
import PIL
from PIL import Image
import os
import re
import subprocess

os.chdir("images")

for pic in os.listdir():
  # Check is the file is a image file
  # If yes, open the file
  try:
    im = Image.open(pic)
    new_pic = im.convert('RGB')

    # Replace format of the file
    name = re.sub(r"(.tiff)$", "", pic)
    new_name = name + "_rotated_and_resized.jpeg"

    # Check is the file has been manipulated
    # If no, rotate, resize, and save with a new name in certain directory
    if re.search("_rotated_and_resized.jpeg", pic) == None:
      new_pic.rotate(-90).resize((128,128)).save(new_name)
      old_place = os.path.abspath(new_name)
      new_place = "/opt/icons/"+ new_name
      subprocess.run(["mv", old_place, new_place])

  except PIL.UnidentifiedImageError:
    pass